### ISSUE TITLE
Cannot convert type 'Fennel.Line' to 'Fennel.CSharp.Metric'

### ISSUE THREAD

**Issue by Alan01252** [dburriss/fennel#1]
In net5.0 project I'm getting the following error when trying to run

`var metric = line as Fennel.CSharp.Metric;`

I can get the tests to run if I clone the project manually and convert the code to net5.0 so I'm not sure entirely why it doesn't work when referencing the nuget package directly ( I'm relatively new to the C# ecosystem ) is there an obvious way around this?

Thanks

Alan

**Comment by Alan01252** [comment]
I am an idiot

**Comment by Alan01252** [comment]
That didn't work either. I think this is because of a difference in the types coming back when using ParseText and ParseLine

**Comment by dburriss** [comment]
Hi @Alan01252 
Welcome to the .NET ecosystem. Thanks for pointing this out.
The lib is written in and designed around F# but I added a C# helper. As you have found, I missed something :D 

Take a look at PR #2 that I am about to merge. `ParseText` will now return a `IEnumerable<ILine>`. It will bump the Fennel version to 0.3.0.
